import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "to-orange-50",
    "bg-orange-*",
    "bg-purple-*",
    "bg-blue-*",
    "border-blue-500/30",
    "border-purple-500/30",
    "border-violet-500/30",
    "bg-violet-500/10",
    "bg-blue-500",
    "bg-blue-50",
    "text-blue-500",
    "bg-green-500",
    "bg-orange-500",
    "bg-purple-500",
    "bg-indigo-500",
    "bg-red-500",
    "text-orange",
    "bg-yellow-500",
    "bg-teal-500",
    "bg-pink-500",
    "bg-gradient-to-r",
    "from-green-50",
    "to-blue-50",
    "from-red-50",
    "via-yellow-50",
    "bg-orange-50",
    "text-orange-700",
    "to-green-50",
    "bg-primary/5",
    "bg-primary/10",
    "bg-red-500",
    "w-3",
    "h-3",
    "bg-primary/20",
    "bg-primary/30",
    "bg-primary/10",
    "bg-primary/5",
    "bg-primary/40",
    "text-blue-500",
    "text-blue-700",
    "text-green-500",
    "to-green-800",
    "to-green-700",
    "to-green-600",
    "to-green-500",
    "to-green-400",
    "text-pink-500",
    "to-green-300",
    "to-green-200",
    "to-green-100",
    "to-green-50",
    "text-yellow",
    "bg-yellow-600",
    "from-green-800",
    "from-green-700",
    "from-green-600",
    "from-green-500",
    "from-green-400",
    "from-green-300",
    "from-green-200",
    "from-green-100",
    "from-green-50",
    "text-primary",
    "border-gray-50",
    "border-blue-500",
    "px-1",
    "px-2",
    "grid",
    "grid-cols-3",
    "gap-4",
    "px-3",
    "px-4",
    "px-5",
    "py-0.5",
    "bg-secondary/20",
    "text-purple-700",
    "bg-purple-50",
    "border-purple-200",
    "text-green-600",
    "text-red-600",
    "text-yellow-600",
    "text-green-700",
    "text-red-700",
    "bg-yellow-50",
    "border-yellow-200",
    "space-y-4",
    "space-y-3",
    "space-y-2",
    "space-y-1",
    "text-lg",
    "text-sm",
    "grid",
    "md:grid-cols-2",
    "gap-4",
    "bg-green-50",
    "bg-red-50",
    "border-green-200",
    "border-red-200",
    "bg-[#232324]",
    "bg-blue-100",
    "bg-blue-500/10",
    "bg-emerald-500/10",
    "bg-red-500/10",
    "bg-gradient-to-br",
    "bg-gray-50",
    "bg-green-100",
    "bg-green-400",
    "bg-green-500/10",
    "bg-green-600",
    "bg-muted",
    "bg-orange-100",
    "bg-orange-500/10",
    "bg-primary",
    "bg-purple-100",
    "bg-red-100",
    "bg-red-400",
    "bg-red-600",
    "bg-white",
    "bg-white/[0.03]",
    "bg-white/[0.04]",
    "bg-yellow-100",
    "bg-yellow-500/10",
    "block",
    "border",
    "border-0",
    "border-blue-200",
    "border-blue-500/20",
    "border-blue-500/25",
    "border-gray-200",
    "border-gray-500",
    "border-green-400",
    "border-green-500",
    "border-green-500/20",
    "border-green-500/25",
    "border-green-500/30",
    "border-l-4",
    "border-orange-200",
    "border-orange-500",
    "border-orange-500/20",
    "border-orange-500/25",
    "border-orange-500/30",
    "border-primary",
    "border-purple-500",
    "border-red-500/20",
    "border-red-500/25",
    "border-red-500/30",
    "border-t",
    "border-violet-500/25",
    "border-violet-500/20",
    "border-white",
    "border-white/10",
    "border-yellow-400",
    "border-yellow-500",
    "border-yellow-500/20",
    "border-yellow-500/30",
    "border-emerald-500/30",
    "container",
    "dark:bg-blue-950/20",
    "dark:bg-green-950/20",
    "dark:bg-orange-950/20",
    "dark:bg-purple-950/20",
    "dark:bg-red-950/20",
    "dark:bg-red-950/30",
    "dark:bg-yellow-950/20",
    "dark:bg-yellow-950/30",
    "dark:border-blue-800",
    "dark:border-green-800",
    "dark:border-orange-800",
    "dark:border-purple-800",
    "dark:border-red-800",
    "dark:border-yellow-800",
    "dark:text-blue-400",
    "dark:text-green-400",
    "dark:text-orange-400",
    "dark:text-purple-400",
    "dark:text-red-200",
    "dark:text-red-400",
    "dark:text-yellow-300",
    "dark:text-yellow-400",
    "flex",
    "flex-1",
    "flex-row",
    "flex-shrink-0",
    "font-bold",
    "font-medium",
    "font-semibold",
    "from-blue-50",
    "from-blue-500/10",
    "from-blue-500/15",
    "from-green-500/15",
    "from-orange-500",
    "from-red-500/10",
    "from-yellow-500/12",
    "gap-2",
    "gap-3",
    "gap-6",
    "grid-cols-1",
    "grid-cols-2",
    "grid-cols-5",
    "h-12",
    "h-16",
    "h-2",
    "h-4",
    "h-5",
    "h-6",
    "h-7",
    "h-8",
    "h-9",
    "h-full",
    "inline-block",
    "inline-flex",
    "items-center",
    "items-start",
    "justify-between",
    "justify-center",
    "justify-end",
    "leading-none",
    "list-decimal",
    "list-disc",
    "list-inside",
    "max-w-4xl",
    "mb-1",
    "mb-2",
    "mb-3",
    "mb-4",
    "mb-5",
    "md:grid-cols-3",
    "md:text-3xl",
    "mr-2",
    "mt-0.5",
    "mt-1",
    "mt-2",
    "mt-3",
    "mt-4",
    "mt-5",
    "mt-6",
    "mx-auto",
    "my-5",
    "my-2",
    "opacity-90",
    "overflow-hidden",
    "p-2",
    "p-0",
    "p-3",
    "p-4",
    "p-5",
    "p-6",
    "pb-4",
    "pl-4",
    "pl-3",
    "pr-2",
    "pt-4",
    "py-4",
    "rounded",
    "rounded-[1.25rem]",
    "rounded-[1.5rem]",
    "rounded-[1rem]",
    "rounded-[2rem]",
    "rounded-full",
    "rounded-lg",
    "rounded-r-lg",
    "rounded-xl",
    "self-center",
    "shadow-[0_0_25px_rgba(34,197,94,0.08)]",
    "shadow-[0_0_25px_rgba(34,197,94,0.10)]",
    "shadow-[0_0_25px_rgba(59,130,246,0.10)]",
    "shadow-[0_0_25px_rgba(139,92,246,0.10)]",
    "shadow-[0_0_25px_rgba(239,68,68,0.10)]",
    "shadow-[0_0_25px_rgba(234,179,8,0.10)]",
    "shadow-[0_0_30px_rgba(34,197,94,0.10)]",
    "shadow-[0_0_30px_rgba(59,130,246,0.10)]",
    "shadow-[0_0_30px_rgba(16,185,129,0.12)]",
    "shadow-[0_0_30px_rgba(249,115,22,0.12)]",
    "shadow-[0_20px_60px_rgba(0,0,0,0.28)]",
    "shadow-none",
    "shrink-0",
    "space-y-5",
    "space-y-6",
    "sm:grid-cols-2",
    "text-2xl",
    "text-3xl",
    "text-[#9a9a9d]",
    "text-[#d7d7db]",
    "text-[#e5e5e7]",
    "text-base",
    "text-blue-300",
    "text-blue-400",
    "text-blue-500/30",
    "text-blue-600",
    "text-center",
    "text-emerald-400",
    "text-green-300",
    "text-green-400",
    "text-indigo-500",
    "text-left",
    "text-md",
    "text-muted-foreground",
    "text-orange-400",
    "text-orange-500",
    "text-orange-600",
    "text-primary-foreground",
    "text-purple-500",
    "text-purple-600",
    "text-red-400",
    "text-red-800",
    "text-right",
    "text-semibold",
    "text-violet-300",
    "text-violet-400",
    "text-white",
    "text-white/80",
    "text-white/90",
    "text-xl",
    "text-yellow-400",
    "text-yellow-500",
    "text-yellow-700",
    "text-yellow-800",
    "to-red-600",
    "to-red-500/10",
    "to-blue-500/15",
    "to-emerald-500/10",
    "to-green-500/10",
    "to-green-500/20",
    "to-green-500/15",
    "to-violet-500/10",
    "to-white/[0.02]",
    "tracking-tight",
    "via-blue-500/10",
    "via-emerald-500/10",
    "via-green-500/10",
    "via-yellow-500/10",
    "via-white/[0.02]",
    "w-12",
    "w-16",
    "w-2",
    "w-4",
    "w-5",
    "w-6",
    "w-7",
    "w-8",
    "w-9",
    "lg:grid-cols-5",
  ],
  theme: {
    extend: {
      colors: {
        valuto: {
          green: {
            50: '#f0fdf4',
            100: '#dcfce7',
            200: '#bbf7d0',
            300: '#86efac',
            400: '#4ade80',
            500: '#22c55e',
            600: '#16a34a',
            700: '#15803d',
            800: '#166534',
            900: '#14532d',
          },
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        hero: {
            DEFAULT: "hsl(var(--hero-bg))",
            foreground: "hsl(var(--hero-foreground))",
            muted: "hsl(var(--hero-muted))",
          },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
          display: ["var(--font-space-grotesk)", "system-ui", "sans-serif"],
          body: ["Inter", "system-ui", "sans-serif"],
        },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
