import {
  Achievement,
  BusinessEvent,
  BusinessIdea,
  Employee,
  MarketingChannel,
} from "@/components/build-your-business/types";

export const BUSINESS_IDEAS: BusinessIdea[] = [
  { id: "clothing", name: "Clothing Brand", icon: "👕", description: "Design and sell your own streetwear or fashion line online.", difficulty: "medium", startingCost: 500, marketDemand: 78, competition: 72, category: "Fashion" },
  { id: "online-store", name: "Online Store", icon: "🛒", description: "Curate and resell trending products through an e-commerce shop.", difficulty: "easy", startingCost: 200, marketDemand: 85, competition: 80, category: "E-Commerce" },
  { id: "tutoring", name: "Tutoring Service", icon: "📚", description: "Offer maths, science or language tutoring to younger students.", difficulty: "easy", startingCost: 50, marketDemand: 70, competition: 55, category: "Education" },
  { id: "tech-app", name: "Tech App", icon: "📱", description: "Build an app that solves a real problem for your generation.", difficulty: "hard", startingCost: 800, marketDemand: 90, competition: 65, category: "Technology" },
  { id: "food", name: "Food Business", icon: "🍰", description: "Start a baking, meal-prep or snack brand from your kitchen.", difficulty: "medium", startingCost: 300, marketDemand: 82, competition: 60, category: "Food & Drink" },
  { id: "creator", name: "Content Creator Brand", icon: "🎬", description: "Monetise your audience through merch, sponsorships and digital products.", difficulty: "medium", startingCost: 100, marketDemand: 88, competition: 75, category: "Media" },
];

export const MARKETING_CHANNELS: MarketingChannel[] = [
  { id: "tiktok", name: "TikTok Ads", icon: "🎵", costPerWeek: 80, conversionRate: 4.2, reach: 5000, description: "Short-form video ads targeting Gen Z audiences." },
  { id: "instagram", name: "Instagram Marketing", icon: "📸", costPerWeek: 60, conversionRate: 3.1, reach: 3500, description: "Stories, Reels and feed posts to build your brand." },
  { id: "influencer", name: "Influencer Partnerships", icon: "⭐", costPerWeek: 200, conversionRate: 5.5, reach: 8000, description: "Partner with creators to promote your product." },
  { id: "word-of-mouth", name: "Word of Mouth", icon: "🗣", costPerWeek: 0, conversionRate: 8.0, reach: 500, description: "Free but slow. Relies on happy customers sharing." },
  { id: "paid-ads", name: "Paid Advertising", icon: "📢", costPerWeek: 150, conversionRate: 3.8, reach: 7000, description: "Google and YouTube ads for broader reach." },
];

export const AVAILABLE_EMPLOYEES: Employee[] = [
  { id: "e1", name: "Alex Chen", role: "Marketing Assistant", productivity: 65, creativity: 80, cost: 120, experience: "junior", avatar: "👩‍💻" },
  { id: "e2", name: "Jordan Smith", role: "Operations Manager", productivity: 85, creativity: 50, cost: 200, experience: "mid", avatar: "👨‍💼" },
  { id: "e3", name: "Sam Williams", role: "Designer", productivity: 70, creativity: 95, cost: 150, experience: "mid", avatar: "🎨" },
  { id: "e4", name: "Taylor Brown", role: "Sales Rep", productivity: 90, creativity: 40, cost: 100, experience: "junior", avatar: "📞" },
  { id: "e5", name: "Morgan Davis", role: "Finance Analyst", productivity: 80, creativity: 30, cost: 250, experience: "senior", avatar: "📊" },
  { id: "e6", name: "Riley Johnson", role: "Social Media Manager", productivity: 75, creativity: 90, cost: 130, experience: "junior", avatar: "📱" },
];

export const BUSINESS_EVENTS: BusinessEvent[] = [
  {
    id: "viral",
    title: "You Went Viral!",
    description: "One of your posts just hit 500K views on TikTok. Customers are flooding in.",
    icon: "🔥",
    type: "positive",
    choices: [
      { id: "v1", text: "Capitalise immediately and launch a flash sale", effects: { revenue: 800, customers: 120, stress: 15 }, lesson: "Timing is everything. Viral moments are rare, so capitalise fast." },
      { id: "v2", text: "Stay calm and build long-term brand value", effects: { revenue: 300, customers: 60, reputation: 10 }, lesson: "Building a lasting brand beats short-term hype." },
    ],
  },
  {
    id: "supplier",
    title: "Supplier Problem",
    description: "Your main supplier just increased prices by 30%. Your margins are at risk.",
    icon: "⚠️",
    type: "negative",
    choices: [
      { id: "s1", text: "Absorb the cost and keep prices the same", effects: { profit: -200, satisfaction: 5 }, lesson: "Absorbing costs protects customers but squeezes your margins." },
      { id: "s2", text: "Find a new cheaper supplier", effects: { profit: -50, satisfaction: -5, stress: 10 }, lesson: "Switching suppliers is risky but can save money long-term." },
      { id: "s3", text: "Raise your prices slightly", effects: { profit: 50, customers: -20, satisfaction: -10 }, lesson: "Price increases can hurt customer loyalty if not handled well." },
    ],
  },
  {
    id: "competitor",
    title: "Competitor Alert",
    description: "A well-funded competitor just launched a very similar product at a lower price.",
    icon: "🏴",
    type: "negative",
    choices: [
      { id: "c1", text: "Differentiate through quality and branding", effects: { reputation: 10, customers: -15, expenses: 100 }, lesson: "Differentiation is your best defence against competitors." },
      { id: "c2", text: "Match their price", effects: { profit: -150, customers: 20 }, lesson: "Price wars erode profits. Compete on value, not only price." },
    ],
  },
  {
    id: "economic",
    title: "Economic Slowdown",
    description: "Consumer spending is dropping. People are being more careful with money.",
    icon: "📉",
    type: "negative",
    choices: [
      { id: "ec1", text: "Cut costs aggressively", effects: { expenses: -200, stress: 20, satisfaction: -10 }, lesson: "Cutting too deep can hurt quality and morale." },
      { id: "ec2", text: "Keep investing and ride it out", effects: { expenses: 100, reputation: 5, customers: -30 }, lesson: "Staying invested during downturns can pay off when recovery hits." },
    ],
  },
  {
    id: "influencer-endorsement",
    title: "Influencer Endorsement!",
    description: "A popular influencer with 2M followers just discovered your brand and loves it.",
    icon: "🌟",
    type: "positive",
    choices: [
      { id: "ie1", text: "Offer them a paid partnership", effects: { expenses: 300, customers: 200, revenue: 1000 }, lesson: "Strategic partnerships can accelerate growth." },
      { id: "ie2", text: "Send free products and hope for organic promotion", effects: { expenses: 50, customers: 80, revenue: 400 }, lesson: "Organic endorsements feel authentic but are less predictable." },
    ],
  },
  {
    id: "press",
    title: "Press Feature",
    description: "A national newspaper wants to feature your startup story.",
    icon: "📰",
    type: "positive",
    choices: [
      { id: "p1", text: "Do the interview and share your journey", effects: { reputation: 15, customers: 50, revenue: 200 }, lesson: "Media coverage builds credibility and trust." },
      { id: "p2", text: "Decline and stay focused on the business", effects: { stress: -5 }, lesson: "Sometimes focus beats publicity, but opportunities are rare." },
    ],
  },
  {
    id: "pop-up-invite",
    title: "Pop-Up Shop Invite",
    description: "A local retail market offers you a stall this weekend.",
    icon: "🛍️",
    type: "positive",
    choices: [
      { id: "pi1", text: "Pay for the stall and go all in", effects: { expenses: 180, revenue: 650, customers: 45, stress: 8 }, lesson: "Offline events can build trust fast when your brand shows up well." },
      { id: "pi2", text: "Decline and stay online only", effects: { stress: -4, satisfaction: 2 }, lesson: "Saying no can preserve focus, but some growth comes from showing up in person." },
    ],
  },
  {
    id: "refund-wave",
    title: "Refund Wave",
    description: "A batch of customers wants refunds after a confusing promotion.",
    icon: "↩️",
    type: "negative",
    choices: [
      { id: "rw1", text: "Refund quickly and apologise", effects: { profit: -250, reputation: 8, satisfaction: 10 }, lesson: "Fast, fair service can turn a mistake into long-term trust." },
      { id: "rw2", text: "Fight every refund request", effects: { profit: 80, reputation: -12, satisfaction: -15 }, lesson: "Protecting short-term cash at the expense of trust usually backfires." },
    ],
  },
  {
    id: "mentor-call",
    title: "Unexpected Mentor Call",
    description: "An experienced founder offers you 30 minutes of free advice.",
    icon: "🧠",
    type: "positive",
    choices: [
      { id: "mc1", text: "Take notes and refine your strategy", effects: { reputation: 5, stress: -8, satisfaction: 6 }, lesson: "Good advice compresses years of mistakes into minutes." },
      { id: "mc2", text: "Brush it off and trust your gut", effects: { satisfaction: 2, stress: 3 }, lesson: "Confidence matters, but refusing feedback can slow your growth." },
    ],
  },
  {
    id: "payment-delay",
    title: "Payment Processor Delay",
    description: "Payouts from your payment platform are delayed for a week.",
    icon: "💳",
    type: "negative",
    choices: [
      { id: "pd1", text: "Pause spend and protect cash", effects: { cash: -100, stress: 8, expenses: -80 }, lesson: "Cash timing matters almost as much as total revenue." },
      { id: "pd2", text: "Keep spending and hope it clears", effects: { cash: -280, stress: 15 }, lesson: "Optimism is not a cash-flow strategy." },
    ],
  },
  {
    id: "customer-story",
    title: "Customer Success Story",
    description: "A customer posts a heartfelt story about how your business helped them.",
    icon: "💬",
    type: "positive",
    choices: [
      { id: "cs1", text: "Share it across your channels", effects: { reputation: 10, customers: 35, revenue: 250 }, lesson: "Social proof is one of the strongest growth levers a young brand has." },
      { id: "cs2", text: "Thank them privately and move on", effects: { satisfaction: 4, stress: -2 }, lesson: "Not every win needs to become content, but stories are powerful." },
    ],
  },
  {
    id: "copycat-account",
    title: "Copycat Account",
    description: "A fake account is reposting your content and confusing customers.",
    icon: "🕵️",
    type: "negative",
    choices: [
      { id: "ca1", text: "Report it and clarify publicly", effects: { reputation: 6, stress: 7, expenses: 40 }, lesson: "Protecting your brand early prevents bigger trust problems later." },
      { id: "ca2", text: "Ignore it for now", effects: { customers: -20, reputation: -8 }, lesson: "Brand confusion quietly drains growth if you do nothing." },
    ],
  },
  {
    id: "bulk-order",
    title: "Bulk Order Request",
    description: "A school or local business wants to place a large one-off order.",
    icon: "📦",
    type: "positive",
    choices: [
      { id: "bo1", text: "Accept with a slight discount", effects: { revenue: 1400, profit: 350, customers: 20, stress: 10 }, lesson: "Big orders can unlock cash and credibility, even at lower margins." },
      { id: "bo2", text: "Decline to avoid operational strain", effects: { stress: -6, satisfaction: 2 }, lesson: "Turning down business can be wise if your operations are not ready." },
    ],
  },
  {
    id: "negative-review",
    title: "Harsh Public Review",
    description: "A customer posts a detailed negative review that starts gaining traction.",
    icon: "⭐",
    type: "negative",
    choices: [
      { id: "nr1", text: "Respond transparently and offer a fix", effects: { reputation: 7, satisfaction: 8, profit: -80 }, lesson: "A strong response can build more trust than a flawless launch." },
      { id: "nr2", text: "Delete comments and go quiet", effects: { reputation: -15, stress: 10 }, lesson: "Silence often looks like guilt when customers want accountability." },
    ],
  },
  {
    id: "packaging-upgrade",
    title: "Packaging Upgrade Opportunity",
    description: "A supplier offers premium packaging that would make your brand look far more polished.",
    icon: "🎁",
    type: "positive",
    choices: [
      { id: "pu1", text: "Upgrade the packaging", effects: { expenses: 160, reputation: 8, satisfaction: 7, customers: 15 }, lesson: "Presentation shapes perceived value more than founders expect." },
      { id: "pu2", text: "Keep the basics for now", effects: { cash: 40, stress: -2 }, lesson: "Cash discipline matters, but branding details can lift conversion." },
    ],
  },
  {
    id: "burnout-week",
    title: "Burnout Week",
    description: "You have been pushing too hard and your energy is crashing.",
    icon: "😵",
    type: "negative",
    choices: [
      { id: "bw1", text: "Take a lighter week", effects: { revenue: -120, stress: -18, satisfaction: 8 }, lesson: "Rest is not laziness. Recovery protects long-term decision quality." },
      { id: "bw2", text: "Push through it", effects: { revenue: 80, stress: 18, satisfaction: -10 }, lesson: "Founders who ignore burnout often pay for it later." },
    ],
  },
  {
    id: "student-ambassador",
    title: "Student Ambassador Program",
    description: "A few enthusiastic customers want to promote your brand on campus.",
    icon: "🎓",
    type: "positive",
    choices: [
      { id: "sa1", text: "Give them discount codes and assets", effects: { expenses: 70, customers: 60, revenue: 350, reputation: 5 }, lesson: "Community-led growth can outperform paid ads when the fit is right." },
      { id: "sa2", text: "Keep marketing tightly controlled", effects: { reputation: 1, stress: -3 }, lesson: "Brand control feels safe, but it can limit organic expansion." },
    ],
  },
  {
    id: "warehouse-mess",
    title: "Stockroom Chaos",
    description: "Your inventory records are wrong and dispatch is getting messy.",
    icon: "📚",
    type: "negative",
    choices: [
      { id: "wm1", text: "Spend time fixing operations", effects: { expenses: 90, stress: 6, satisfaction: 6 }, lesson: "Operations are invisible when they work and brutal when they do not." },
      { id: "wm2", text: "Patch it up manually", effects: { customers: -15, stress: 12 }, lesson: "Temporary fixes become expensive when a business starts scaling." },
    ],
  },
  {
    id: "podcast-invite",
    title: "Podcast Invite",
    description: "A niche business podcast wants to interview you about your journey.",
    icon: "🎙️",
    type: "positive",
    choices: [
      { id: "po1", text: "Say yes and tell the story", effects: { reputation: 9, customers: 25, revenue: 180 }, lesson: "Founders who communicate well compound trust over time." },
      { id: "po2", text: "Skip it and keep building", effects: { stress: -4 }, lesson: "Sometimes focused execution beats visibility, but audiences take time to build." },
    ],
  },
  {
    id: "freelancer-flop",
    title: "Freelancer Letdown",
    description: "A contractor misses a deadline and your launch assets are late.",
    icon: "🧩",
    type: "negative",
    choices: [
      { id: "ff1", text: "Pay for a replacement urgently", effects: { expenses: 180, stress: 10, reputation: 4 }, lesson: "Cheap shortcuts often become expensive when time matters." },
      { id: "ff2", text: "Delay the campaign", effects: { revenue: -180, stress: 4 }, lesson: "Delays can protect quality, but they usually cost momentum." },
    ],
  },
  {
    id: "loyalty-program",
    title: "Loyalty Program Idea",
    description: "You are considering a simple reward scheme for repeat customers.",
    icon: "🎟️",
    type: "positive",
    choices: [
      { id: "lp1", text: "Launch it now", effects: { expenses: 90, customers: 35, satisfaction: 12, revenue: 220 }, lesson: "Retention is often cheaper and stronger than constant acquisition." },
      { id: "lp2", text: "Wait until you are bigger", effects: { cash: 20, satisfaction: -2 }, lesson: "Even tiny businesses can benefit from giving customers a reason to return." },
    ],
  },
  {
    id: "feature-creep",
    title: "Feature Creep",
    description: "You keep adding extras to the product and the launch is slipping.",
    icon: "🧱",
    type: "negative",
    choices: [
      { id: "fc1", text: "Cut back to the essentials", effects: { stress: -8, satisfaction: 4, reputation: 3 }, lesson: "A finished simple product usually beats a perfect unfinished one." },
      { id: "fc2", text: "Keep adding more", effects: { expenses: 120, stress: 14, revenue: -100 }, lesson: "Scope creep kills momentum and cash." },
    ],
  },
  {
    id: "award-shortlist",
    title: "Awards Shortlist",
    description: "Your startup is shortlisted for a regional young business award.",
    icon: "🏅",
    type: "positive",
    choices: [
      { id: "as1", text: "Promote the shortlist everywhere", effects: { reputation: 12, customers: 28, revenue: 150 }, lesson: "Third-party credibility can amplify trust fast." },
      { id: "as2", text: "Stay humble and quiet", effects: { satisfaction: 3, stress: -2 }, lesson: "Humility is fine, but social proof can open doors." },
    ],
  },
  {
    id: "website-crash",
    title: "Website Crash",
    description: "Traffic spikes and your site goes down at the worst possible time.",
    icon: "💥",
    type: "negative",
    choices: [
      { id: "wc1", text: "Pay for urgent technical help", effects: { expenses: 220, stress: 10, reputation: 5 }, lesson: "Infrastructure feels boring until it breaks during demand." },
      { id: "wc2", text: "Wait and hope it comes back", effects: { customers: -35, revenue: -260, reputation: -8 }, lesson: "Outages cost more than money. They damage trust." },
    ],
  },
  {
    id: "newsletter-boom",
    title: "Newsletter Boom",
    description: "An email campaign performs far better than expected.",
    icon: "📬",
    type: "positive",
    choices: [
      { id: "nb1", text: "Double down on email", effects: { revenue: 420, customers: 40, reputation: 4 }, lesson: "Owned channels are valuable because you control the audience." },
      { id: "nb2", text: "Treat it as a one-off win", effects: { revenue: 100, stress: -2 }, lesson: "Repeatable systems matter more than lucky spikes." },
    ],
  },
  {
    id: "tax-bill",
    title: "Unexpected Tax Bill",
    description: "A tax payment lands sooner than you planned for.",
    icon: "🧾",
    type: "negative",
    choices: [
      { id: "tb1", text: "Pay it and tighten spending", effects: { cash: -350, stress: 10, expenses: -60 }, lesson: "Profit is not the same as cash in the bank. Set money aside for tax." },
      { id: "tb2", text: "Delay and hope to catch up later", effects: { cash: -150, reputation: -4, stress: 18 }, lesson: "Avoiding obligations usually makes them worse." },
    ],
  },
  {
    id: "angel-interest",
    title: "Angel Investor Interest",
    description: "A small angel investor wants to meet after seeing your traction.",
    icon: "👼",
    type: "positive",
    choices: [
      { id: "ai1", text: "Take the meeting seriously", effects: { valuation: 12000, reputation: 6, stress: 5 }, lesson: "Capital follows traction, but founders should prepare before pitching." },
      { id: "ai2", text: "Ignore it and bootstrap", effects: { satisfaction: 5, stress: -3 }, lesson: "Not every business needs funding, but good investor relationships can help later." },
    ],
  },
  {
    id: "team-conflict",
    title: "Team Conflict",
    description: "Two people helping the business disagree publicly about priorities.",
    icon: "🔥",
    type: "negative",
    choices: [
      { id: "tc1", text: "Address it directly and mediate", effects: { stress: 8, satisfaction: 6, reputation: 3 }, lesson: "People problems become business problems if you avoid them." },
      { id: "tc2", text: "Ignore it and hope it fades", effects: { stress: 14, satisfaction: -8, reputation: -5 }, lesson: "Unresolved conflict drains energy and execution." },
    ],
  },
  {
    id: "holiday-surge",
    title: "Holiday Surge",
    description: "Seasonal demand spikes hard and customers are ready to buy.",
    icon: "🎄",
    type: "positive",
    choices: [
      { id: "hs1", text: "Run a themed promotion", effects: { revenue: 900, customers: 95, stress: 12 }, lesson: "Seasonality can create breakout moments if you prepare for it." },
      { id: "hs2", text: "Keep things steady", effects: { revenue: 220, stress: -1 }, lesson: "Not every brand should chase every peak, but missed windows can be costly." },
    ],
  },
  {
    id: "shipping-delays",
    title: "Shipping Delays",
    description: "Delivery times suddenly get worse and complaints begin rising.",
    icon: "🚚",
    type: "negative",
    choices: [
      { id: "sd1", text: "Upgrade to faster shipping", effects: { expenses: 180, satisfaction: 10, reputation: 6 }, lesson: "Delivery is part of the customer experience, not just an operational detail." },
      { id: "sd2", text: "Wait it out", effects: { customers: -25, satisfaction: -10, reputation: -6 }, lesson: "Slow delivery quietly erodes brand trust." },
    ],
  },
  {
    id: "b2b-lead",
    title: "B2B Lead",
    description: "A business customer asks if you can supply them regularly.",
    icon: "🤝",
    type: "positive",
    choices: [
      { id: "bl1", text: "Pursue the contract", effects: { revenue: 1100, customers: 10, valuation: 6000, stress: 8 }, lesson: "Recurring business clients can stabilise revenue." },
      { id: "bl2", text: "Stay focused on consumers", effects: { satisfaction: 4, stress: -4 }, lesson: "Focus is valuable, but wholesale and B2B can diversify risk." },
    ],
  },
  {
    id: "hype-trend",
    title: "Trend Explosion",
    description: "A sudden online trend fits your product perfectly.",
    icon: "📈",
    type: "positive",
    choices: [
      { id: "ht1", text: "Lean into the trend immediately", effects: { revenue: 700, customers: 85, stress: 10 }, lesson: "Speed wins when attention cycles move fast." },
      { id: "ht2", text: "Protect the brand and ignore the trend", effects: { reputation: 6, revenue: 80 }, lesson: "Brand discipline can matter more than chasing every moment." },
    ],
  },
  {
    id: "price-backlash",
    title: "Price Backlash",
    description: "Customers react badly to your latest pricing update.",
    icon: "💸",
    type: "negative",
    choices: [
      { id: "pb1", text: "Explain the value and stand firm", effects: { reputation: 4, customers: -12, profit: 90 }, lesson: "Price increases land better when customers understand the value." },
      { id: "pb2", text: "Reverse it immediately", effects: { satisfaction: 8, profit: -130 }, lesson: "Panic pricing trains customers to resist every increase." },
    ],
  },
  {
    id: "ugc-wave",
    title: "UGC Wave",
    description: "Customers start making content about your brand without being asked.",
    icon: "📱",
    type: "positive",
    choices: [
      { id: "uw1", text: "Feature their posts publicly", effects: { customers: 70, reputation: 8, revenue: 280 }, lesson: "User-generated content turns customers into marketers." },
      { id: "uw2", text: "Leave it alone", effects: { satisfaction: 2 }, lesson: "Community momentum grows faster when the brand acknowledges it." },
    ],
  },
  {
    id: "supplier-exclusive",
    title: "Exclusive Supplier Offer",
    description: "A supplier offers you better rates if you commit to a longer deal.",
    icon: "🔐",
    type: "positive",
    choices: [
      { id: "se1", text: "Lock in the deal", effects: { expenses: -140, profit: 120, stress: -3 }, lesson: "Negotiation and predictability can protect margins." },
      { id: "se2", text: "Stay flexible", effects: { satisfaction: 3 }, lesson: "Flexibility is useful, but certainty has value in volatile periods." },
    ],
  },
  {
    id: "copy-error",
    title: "Copy Error",
    description: "A typo in your marketing makes the brand look sloppy.",
    icon: "✍️",
    type: "negative",
    choices: [
      { id: "ce1", text: "Correct it fast and own it", effects: { reputation: 4, stress: 3 }, lesson: "Small mistakes matter less when corrected quickly and honestly." },
      { id: "ce2", text: "Pretend nobody noticed", effects: { reputation: -6, satisfaction: -4 }, lesson: "Attention to detail compounds in brand building." },
    ],
  },
  {
    id: "factory-minimums",
    title: "Supplier Minimums",
    description: "A manufacturer wants you to order more stock than planned.",
    icon: "🏭",
    type: "negative",
    choices: [
      { id: "fm1", text: "Order the larger batch", effects: { cash: -450, revenue: 180, stress: 12 }, lesson: "Inventory can unlock scale, but it ties up precious cash." },
      { id: "fm2", text: "Walk away and stay lean", effects: { stress: -2, satisfaction: 2 }, lesson: "Lean operations reduce risk even if they limit upside." },
    ],
  },
  {
    id: "community-event",
    title: "Community Event",
    description: "A youth entrepreneurship event invites you to exhibit.",
    icon: "🎪",
    type: "positive",
    choices: [
      { id: "co1", text: "Show up and network hard", effects: { reputation: 10, customers: 30, valuation: 4000 }, lesson: "Visibility and relationships open doors that ads cannot." },
      { id: "co2", text: "Pass on the event", effects: { stress: -3 }, lesson: "Protecting focus matters, but local ecosystems can accelerate growth." },
    ],
  },
  {
    id: "team-superstar",
    title: "Team Superstar",
    description: "Someone helping the business goes above and beyond this week.",
    icon: "🌟",
    type: "positive",
    choices: [
      { id: "ts1", text: "Reward them properly", effects: { expenses: 100, satisfaction: 12, revenue: 250, reputation: 4 }, lesson: "Great people are worth recognising before they burn out or leave." },
      { id: "ts2", text: "Take the win and move on", effects: { revenue: 120 }, lesson: "Teams stay strong when effort is recognised, not assumed." },
    ],
  },
  {
    id: "customer-support-flood",
    title: "Support Inbox Flood",
    description: "A jump in customers leads to a pile-up of support messages.",
    icon: "📨",
    type: "negative",
    choices: [
      { id: "cf1", text: "Spend time fixing support", effects: { revenue: -90, satisfaction: 10, reputation: 5 }, lesson: "Service quality matters most when growth arrives." },
      { id: "cf2", text: "Focus only on sales", effects: { customers: -18, satisfaction: -12, stress: 9 }, lesson: "Ignoring support is a hidden tax on future growth." },
    ],
  },
  {
    id: "new-market",
    title: "New Market Opportunity",
    description: "You see signs your product could work for a different customer segment too.",
    icon: "🗺️",
    type: "positive",
    choices: [
      { id: "nm1", text: "Test a new segment carefully", effects: { customers: 40, valuation: 6000, stress: 6 }, lesson: "Expansion works best as a test, not a leap of faith." },
      { id: "nm2", text: "Stick to your original audience", effects: { reputation: 3, stress: -2 }, lesson: "Clarity beats sprawl when the core business is still forming." },
    ],
  },
  {
    id: "subscription-idea",
    title: "Subscription Idea",
    description: "You spot a way to make customers buy repeatedly through a subscription.",
    icon: "🔁",
    type: "positive",
    choices: [
      { id: "si1", text: "Pilot a subscription option", effects: { revenue: 450, valuation: 9000, customers: 20 }, lesson: "Recurring revenue makes businesses more resilient and valuable." },
      { id: "si2", text: "Keep things one-off for now", effects: { satisfaction: 2 }, lesson: "Subscriptions are powerful, but only if the value is consistent." },
    ],
  },
  {
    id: "discount-expectation",
    title: "Discount Expectation",
    description: "Customers now wait for offers instead of buying at full price.",
    icon: "🏷️",
    type: "negative",
    choices: [
      { id: "de1", text: "Reduce discounting and retrain demand", effects: { customers: -10, profit: 120, reputation: 3 }, lesson: "Too many discounts train customers to undervalue your brand." },
      { id: "de2", text: "Keep the offers flowing", effects: { revenue: 150, profit: -90, satisfaction: 6 }, lesson: "Discounts can boost top-line sales while quietly weakening the business." },
    ],
  },
  {
    id: "photo-upgrade",
    title: "Product Photography Upgrade",
    description: "A better visual identity could make your product look far more premium.",
    icon: "📸",
    type: "positive",
    choices: [
      { id: "ph1", text: "Invest in better visuals", effects: { expenses: 150, revenue: 260, reputation: 7, customers: 18 }, lesson: "Strong visuals lift trust, conversion, and perceived value." },
      { id: "ph2", text: "Use the old assets", effects: { cash: 25 }, lesson: "You can save money now, but weak presentation can suppress growth." },
    ],
  },
  {
    id: "chargeback-hit",
    title: "Chargeback Hit",
    description: "A spike in payment disputes hits your account.",
    icon: "💥",
    type: "negative",
    choices: [
      { id: "ch1", text: "Tighten policies and verify orders", effects: { profit: -120, reputation: 4, stress: 7 }, lesson: "Fraud controls feel painful until you need them." },
      { id: "ch2", text: "Accept the losses for now", effects: { cash: -220, stress: 10 }, lesson: "Leakage compounds fast when no one plugs it." },
    ],
  },
  {
    id: "retail-buyer",
    title: "Retail Buyer Interest",
    description: "A shop buyer wants to discuss stocking your product.",
    icon: "🏬",
    type: "positive",
    choices: [
      { id: "rb1", text: "Prepare a wholesale pitch", effects: { revenue: 850, customers: 30, valuation: 8000, stress: 8 }, lesson: "Wholesale can increase reach quickly, but margins and operations matter." },
      { id: "rb2", text: "Stay direct-to-consumer only", effects: { satisfaction: 4 }, lesson: "Owning the customer relationship has real value too." },
    ],
  },
  {
    id: "founder-doubt",
    title: "Founder Doubt",
    description: "You start questioning whether the business is really working.",
    icon: "🌧️",
    type: "negative",
    choices: [
      { id: "fd1", text: "Review the numbers and reset goals", effects: { stress: -12, satisfaction: 7, reputation: 2 }, lesson: "Clarity often comes from data, not emotion." },
      { id: "fd2", text: "Spiral and avoid decisions", effects: { stress: 16, revenue: -100 }, lesson: "Indecision is expensive when momentum is fragile." },
    ],
  },
  {
    id: "charity-collab",
    title: "Charity Collaboration",
    description: "A local cause asks to partner on a limited campaign.",
    icon: "❤️",
    type: "positive",
    choices: [
      { id: "cc1", text: "Run the collaboration", effects: { reputation: 12, customers: 22, revenue: 140, profit: -40 }, lesson: "Purpose-led campaigns can deepen brand meaning when they are authentic." },
      { id: "cc2", text: "Decline politely", effects: { stress: -2 }, lesson: "Not every opportunity fits, but values shape reputation over time." },
    ],
  },
  {
    id: "trend-dies",
    title: "Trend Dies Overnight",
    description: "A trend you were benefiting from suddenly disappears.",
    icon: "📉",
    type: "negative",
    choices: [
      { id: "td1", text: "Refocus on evergreen demand", effects: { revenue: -120, reputation: 5, stress: 6 }, lesson: "Trends are temporary. Durable demand is safer." },
      { id: "td2", text: "Chase the next trend immediately", effects: { stress: 12, customers: 8, satisfaction: -4 }, lesson: "Constantly chasing hype can make a brand feel unstable." },
    ],
  },
  {
    id: "micro-creator-army",
    title: "Micro-Creator Army",
    description: "Several small creators want to collaborate at once.",
    icon: "🎥",
    type: "positive",
    choices: [
      { id: "ma1", text: "Activate all of them", effects: { expenses: 220, revenue: 700, customers: 90, reputation: 5 }, lesson: "Smaller creators can collectively outperform one expensive influencer." },
      { id: "ma2", text: "Choose only one or two", effects: { expenses: 80, revenue: 220, customers: 25 }, lesson: "Curated partnerships can still work if the fit is strong." },
    ],
  },
  {
    id: "quality-breakthrough",
    title: "Quality Breakthrough",
    description: "A process improvement makes your product meaningfully better.",
    icon: "🛠️",
    type: "positive",
    choices: [
      { id: "qb1", text: "Promote the improvement heavily", effects: { reputation: 10, satisfaction: 12, customers: 20, revenue: 180 }, lesson: "Quality compounds when customers can feel the difference." },
      { id: "qb2", text: "Quietly implement it", effects: { satisfaction: 6, stress: -2 }, lesson: "Not every improvement needs marketing, but communication can unlock more value." },
    ],
  },
  {
    id: "late-invoice",
    title: "Late Invoice",
    description: "A client or partner is slow to pay and your cash plan gets messy.",
    icon: "⏰",
    type: "negative",
    choices: [
      { id: "li1", text: "Chase payment professionally", effects: { cash: -80, reputation: 2, stress: 4 }, lesson: "Payment discipline is a core business skill, not an awkward afterthought." },
      { id: "li2", text: "Let it slide for now", effects: { cash: -220, stress: 9 }, lesson: "Slow payers create real operational pain if you allow it." },
    ],
  },
  {
    id: "brand-refresh",
    title: "Brand Refresh Debate",
    description: "Your visuals feel dated and you are considering a refresh.",
    icon: "🎨",
    type: "positive",
    choices: [
      { id: "br1", text: "Refresh the brand carefully", effects: { expenses: 140, reputation: 8, customers: 18, valuation: 3000 }, lesson: "Brands should evolve without losing what customers already trust." },
      { id: "br2", text: "Leave it unchanged", effects: { cash: 20 }, lesson: "Stability saves money, but outdated brands can feel invisible." },
    ],
  },
  {
    id: "returns-policy",
    title: "Returns Policy Debate",
    description: "Customers want a friendlier returns policy before buying.",
    icon: "📄",
    type: "positive",
    choices: [
      { id: "rp1", text: "Make returns easier", effects: { satisfaction: 12, customers: 25, profit: -70 }, lesson: "Lower friction can improve conversion even if it costs a little." },
      { id: "rp2", text: "Keep the strict policy", effects: { profit: 40, customers: -12, reputation: -3 }, lesson: "Policies shape trust as much as product quality does." },
    ],
  },
  {
    id: "university-partnership",
    title: "University Partnership",
    description: "A college society wants to partner with your brand for an event.",
    icon: "🏫",
    type: "positive",
    choices: [
      { id: "up1", text: "Sponsor the event", effects: { expenses: 100, customers: 55, revenue: 240, reputation: 7 }, lesson: "Niche communities can unlock highly relevant demand." },
      { id: "up2", text: "Skip it", effects: { stress: -2 }, lesson: "You cannot do every partnership, but aligned communities matter." },
    ],
  },
  {
    id: "customer-club",
    title: "Customer Club",
    description: "Your most loyal buyers want a closer community around the brand.",
    icon: "🫶",
    type: "positive",
    choices: [
      { id: "cu1", text: "Build a VIP group", effects: { customers: 30, satisfaction: 14, reputation: 6, revenue: 180 }, lesson: "Strong communities defend brands during hard seasons." },
      { id: "cu2", text: "Keep things transactional", effects: { satisfaction: -2 }, lesson: "Transactional brands can grow, but communities deepen loyalty." },
    ],
  },
  {
    id: "energy-bills",
    title: "Energy Bill Shock",
    description: "Operating costs rise suddenly and squeeze your cash position.",
    icon: "⚡",
    type: "negative",
    choices: [
      { id: "eb1", text: "Cut waste elsewhere", effects: { expenses: -100, stress: 6, satisfaction: -2 }, lesson: "When costs rise, disciplined operators adapt quickly." },
      { id: "eb2", text: "Absorb the hit", effects: { cash: -180, stress: 10 }, lesson: "Silent cost inflation can hurt more than obvious one-off mistakes." },
    ],
  },
  {
    id: "referral-boom",
    title: "Referral Boom",
    description: "Customers start referring friends without prompting.",
    icon: "📣",
    type: "positive",
    choices: [
      { id: "re1", text: "Reward referrals", effects: { expenses: 80, customers: 75, revenue: 320, reputation: 4 }, lesson: "People trust recommendations more than ads." },
      { id: "re2", text: "Let it happen naturally", effects: { customers: 30, revenue: 120 }, lesson: "Organic momentum is powerful, but systems can amplify it." },
    ],
  },
  {
    id: "compliance-check",
    title: "Compliance Check",
    description: "A platform or regulator requests clearer disclosures from your business.",
    icon: "🛡️",
    type: "negative",
    choices: [
      { id: "ck1", text: "Fix everything properly", effects: { expenses: 140, reputation: 5, stress: 7 }, lesson: "Compliance feels tedious until it protects the business." },
      { id: "ck2", text: "Do the minimum", effects: { cash: 20, reputation: -6, stress: 10 }, lesson: "Cutting corners on trust and compliance is risky." },
    ],
  },
  {
    id: "international-orders",
    title: "International Orders",
    description: "Customers from abroad start asking to buy from you.",
    icon: "🌍",
    type: "positive",
    choices: [
      { id: "io1", text: "Open international shipping", effects: { revenue: 500, customers: 45, valuation: 5000, stress: 9 }, lesson: "New markets bring upside, but complexity rises too." },
      { id: "io2", text: "Stay domestic for now", effects: { stress: -4, satisfaction: 2 }, lesson: "Geographic focus can be smart when systems are still fragile." },
    ],
  },
  {
    id: "mini-scandal",
    title: "Mini Brand Scandal",
    description: "A poorly worded post causes backlash and customers want an explanation.",
    icon: "🚨",
    type: "negative",
    choices: [
      { id: "ms1", text: "Apologise clearly and learn from it", effects: { reputation: 4, stress: 10, satisfaction: 6 }, lesson: "How a founder responds to mistakes shapes long-term trust." },
      { id: "ms2", text: "Defend yourself publicly", effects: { reputation: -14, stress: 14, customers: -18 }, lesson: "Defensiveness often deepens reputational damage." },
    ],
  },
  {
    id: "surprise-wholesale-repeat",
    title: "Repeat Wholesale Order",
    description: "A previous bulk customer comes back with an even bigger reorder.",
    icon: "🔁",
    type: "positive",
    choices: [
      { id: "sw1", text: "Prioritise the repeat order", effects: { revenue: 1600, profit: 420, valuation: 10000, stress: 12 }, lesson: "Repeat commercial demand is a strong signal of product-market fit." },
      { id: "sw2", text: "Limit the order to protect capacity", effects: { revenue: 500, stress: -3, satisfaction: 3 }, lesson: "Sustainable growth sometimes means saying not yet, not never." },
    ],
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  { id: "first-sale", title: "First Sale!", description: "Earned your first revenue", icon: "💰", unlocked: false, condition: (m) => m.revenue > 0 },
  { id: "revenue-250", title: "Starter Stripe", description: "Reach £400 in total revenue", icon: "🪙", unlocked: false, condition: (m) => m.revenue >= 400 },
  { id: "revenue-500", title: "Halfway Hustle", description: "Reach £900 in total revenue", icon: "🥈", unlocked: false, condition: (m) => m.revenue >= 900 },
  { id: "revenue-1000", title: "£1K Club", description: "Hit £1,800 total revenue", icon: "📈", unlocked: false, condition: (m) => m.revenue >= 1800 },
  { id: "revenue-2500", title: "Momentum Maker", description: "Reach £3,500 in total revenue", icon: "🚴", unlocked: false, condition: (m) => m.revenue >= 3500 },
  { id: "revenue-5000", title: "£5K Revenue", description: "Reach £6,500 in total revenue", icon: "🚀", unlocked: false, condition: (m) => m.revenue >= 6500 },
  { id: "revenue-7500", title: "Scaling Signal", description: "Reach £9,000 in total revenue", icon: "📡", unlocked: false, condition: (m) => m.revenue >= 9000 },
  { id: "revenue-10000", title: "£10K Revenue", description: "Reach £10,000 in total revenue", icon: "💎", unlocked: false, condition: (m) => m.revenue >= 10000 },
  { id: "revenue-15000", title: "Growth Gear", description: "Reach £15,000 in total revenue", icon: "⚙️", unlocked: false, condition: (m) => m.revenue >= 15000 },
  { id: "revenue-25000", title: "Quarter-Century Sales", description: "Reach £25,000 in total revenue", icon: "🏁", unlocked: false, condition: (m) => m.revenue >= 25000 },
  { id: "revenue-50000", title: "£50K Run", description: "Reach £50,000 in total revenue", icon: "🔥", unlocked: false, condition: (m) => m.revenue >= 50000 },
  { id: "revenue-100000", title: "Six Figure Revenue", description: "Reach £100,000 in total revenue", icon: "🏦", unlocked: false, condition: (m) => m.revenue >= 100000 },
  { id: "revenue-250000", title: "Revenue Rocket", description: "Reach £250,000 in total revenue", icon: "🚀", unlocked: false, condition: (m) => m.revenue >= 250000 },
  { id: "revenue-500000", title: "Half-Million Seller", description: "Reach £500,000 in total revenue", icon: "👑", unlocked: false, condition: (m) => m.revenue >= 500000 },
  { id: "profitable", title: "Profitable Business", description: "Your total profit turns positive", icon: "✅", unlocked: false, condition: (m) => m.profit > 0 },
  { id: "profit-100", title: "First Real Margin", description: "Reach £250 in total profit", icon: "💷", unlocked: false, condition: (m) => m.profit >= 250 },
  { id: "profit-1000", title: "Profit Engine", description: "Reach £1,500 in total profit", icon: "🏎️", unlocked: false, condition: (m) => m.profit >= 1500 },
  { id: "profit-5000", title: "Cash Machine", description: "Reach £5,000 in total profit", icon: "🏧", unlocked: false, condition: (m) => m.profit >= 5000 },
  { id: "profit-10000", title: "Serious Margins", description: "Reach £10,000 in total profit", icon: "🧮", unlocked: false, condition: (m) => m.profit >= 10000 },
  { id: "profit-25000", title: "Profit Pro", description: "Reach £25,000 in total profit", icon: "📊", unlocked: false, condition: (m) => m.profit >= 25000 },
  { id: "profit-50000", title: "Founder Payday", description: "Reach £50,000 in total profit", icon: "💼", unlocked: false, condition: (m) => m.profit >= 50000 },
  { id: "cash-2000", title: "Cash Cushion", description: "Build your cash balance to £3,000", icon: "🛟", unlocked: false, condition: (m) => m.cash >= 3000 },
  { id: "cash-5000", title: "Cash is King", description: "Build your cash balance to £7,500", icon: "👛", unlocked: false, condition: (m) => m.cash >= 7500 },
  { id: "cash-10000", title: "War Chest", description: "Build your cash balance to £10,000", icon: "🧰", unlocked: false, condition: (m) => m.cash >= 10000 },
  { id: "cash-25000", title: "Operator's Reserve", description: "Build your cash balance to £25,000", icon: "🏦", unlocked: false, condition: (m) => m.cash >= 25000 },
  { id: "cash-50000", title: "Capital Stack", description: "Build your cash balance to £50,000", icon: "💳", unlocked: false, condition: (m) => m.cash >= 50000 },
  { id: "customer-1", title: "Customer Number One", description: "Win 3 customers", icon: "🙌", unlocked: false, condition: (m) => m.customers >= 3 },
  { id: "customer-5", title: "First Five", description: "Serve 8 customers", icon: "🖐️", unlocked: false, condition: (m) => m.customers >= 8 },
  { id: "customer-10", title: "Tiny Fan Club", description: "Serve 18 customers", icon: "🎉", unlocked: false, condition: (m) => m.customers >= 18 },
  { id: "customer-25", title: "Word is Spreading", description: "Serve 35 customers", icon: "📣", unlocked: false, condition: (m) => m.customers >= 35 },
  { id: "customer-50", title: "First 50 Customers", description: "Serve 65 customers", icon: "🤝", unlocked: false, condition: (m) => m.customers >= 65 },
  { id: "customer-100", title: "100 Customers", description: "Serve 100 customers", icon: "👥", unlocked: false, condition: (m) => m.customers >= 100 },
  { id: "customer-250", title: "Community Builder", description: "Serve 250 customers", icon: "🏘️", unlocked: false, condition: (m) => m.customers >= 250 },
  { id: "customer-500", title: "Crowd Favourite", description: "Serve 500 customers", icon: "🎪", unlocked: false, condition: (m) => m.customers >= 500 },
  { id: "customer-1000", title: "Four Figure Customers", description: "Serve 1,000 customers", icon: "🌍", unlocked: false, condition: (m) => m.customers >= 1000 },
  { id: "customer-5000", title: "Mass Market", description: "Serve 5,000 customers", icon: "🏟️", unlocked: false, condition: (m) => m.customers >= 5000 },
  { id: "rep-60", title: "Promising Reputation", description: "Reach 65 reputation after £1,500 revenue", icon: "👍", unlocked: false, condition: (m) => m.revenue >= 1500 && m.reputation >= 65 },
  { id: "rep-70", title: "Respected Brand", description: "Reach 75 reputation after £4,000 revenue", icon: "🌟", unlocked: false, condition: (m) => m.revenue >= 4000 && m.reputation >= 75 },
  { id: "rep-80", title: "Trusted Brand", description: "Reach 80 reputation", icon: "⭐", unlocked: false, condition: (m) => m.reputation >= 80 },
  { id: "rep-90", title: "Loved Brand", description: "Reach 90 reputation", icon: "💚", unlocked: false, condition: (m) => m.reputation >= 90 },
  { id: "rep-100", title: "Untouchable Reputation", description: "Reach 100 reputation", icon: "👑", unlocked: false, condition: (m) => m.reputation >= 100 },
  { id: "satisfaction-80", title: "Happy Customers", description: "Reach 82 satisfaction after £2,000 revenue", icon: "😊", unlocked: false, condition: (m) => m.revenue >= 2000 && m.satisfaction >= 82 },
  { id: "satisfaction-90", title: "Delight Delivered", description: "Reach 92 satisfaction after £8,000 revenue", icon: "😍", unlocked: false, condition: (m) => m.revenue >= 8000 && m.satisfaction >= 92 },
  { id: "satisfaction-95", title: "Customer Obsession", description: "Reach 95 satisfaction", icon: "🫶", unlocked: false, condition: (m) => m.satisfaction >= 95 },
  { id: "stress-master", title: "Calm Operator", description: "Keep stress at 25 or below after £3,000 revenue", icon: "🧘", unlocked: false, condition: (m) => m.revenue >= 3000 && m.stress <= 25 },
  { id: "balanced-builder", title: "Balanced Builder", description: "Keep satisfaction above 82 and stress below 35 after £5,000 revenue", icon: "⚖️", unlocked: false, condition: (m) => m.revenue >= 5000 && m.satisfaction >= 82 && m.stress <= 35 },
  { id: "efficient-engine", title: "Efficient Engine", description: "Keep weekly costs under 45% of weekly revenue after £2,500 revenue", icon: "🔧", unlocked: false, condition: (m) => m.revenue >= 2500 && m.weeklyRevenue >= 250 && m.weeklyCosts <= m.weeklyRevenue * 0.45 },
  { id: "margin-monster", title: "Margin Monster", description: "Hold a total profit margin of at least 30%", icon: "🦈", unlocked: false, condition: (m) => m.revenue >= 5000 && m.profit / m.revenue >= 0.3 },
  { id: "lean-machine", title: "Lean Machine", description: "Reach profitability with expenses under £2,000", icon: "🪶", unlocked: false, condition: (m) => m.profit > 0 && m.expenses <= 2000 },
  { id: "valuation-10000", title: "Valuation Spark", description: "Reach a £15,000 valuation", icon: "✨", unlocked: false, condition: (m) => m.valuation >= 15000 },
  { id: "valuation-25000", title: "Investor Eyebrows", description: "Reach a £35,000 valuation", icon: "👀", unlocked: false, condition: (m) => m.valuation >= 35000 },
  { id: "valuation-50000", title: "Serious Venture", description: "Reach a £50,000 valuation", icon: "🏗️", unlocked: false, condition: (m) => m.valuation >= 50000 },
  { id: "valuation-100000", title: "£100K Valuation", description: "Reach a £100,000 valuation", icon: "🏆", unlocked: false, condition: (m) => m.valuation >= 100000 },
  { id: "valuation-250000", title: "Quarter-Million Vision", description: "Reach a £250,000 valuation", icon: "🛰️", unlocked: false, condition: (m) => m.valuation >= 250000 },
  { id: "valuation-500000", title: "Half-Million Company", description: "Reach a £500,000 valuation", icon: "🏢", unlocked: false, condition: (m) => m.valuation >= 500000 },
  { id: "valuation-1000000", title: "Million-Pound Business", description: "Reach a £1,000,000 valuation", icon: "💠", unlocked: false, condition: (m) => m.valuation >= 1000000 },
  { id: "valuation-5000000", title: "Scale Legend", description: "Reach a £5,000,000 valuation", icon: "🌠", unlocked: false, condition: (m) => m.valuation >= 5000000 },
];

export const BUSINESS_LESSONS: Record<string, string> = {
  "low-price": "Low margins make scaling difficult. Every pound counts when you're growing.",
  "no-marketing": "Great products still need marketing. If nobody knows about you, nobody can buy.",
  overspend: "Rapid growth without financial control can cause failure. Watch your cash flow.",
  "high-stress": "Burnout is real. Even entrepreneurs need balance to make good decisions.",
  "good-reputation": "A strong reputation compounds over time. Word-of-mouth is priceless.",
  diversify: "Do not rely on one income stream. Diversification reduces risk.",
  retention: "Keeping an existing customer is often cheaper and more profitable than acquiring a new one.",
  operations: "Operational problems feel small until they break customer experience at scale.",
  cashflow: "A business can be profitable on paper and still fail if cash arrives too late.",
  positioning: "If customers do not know why you are different, price becomes the only comparison.",
  community: "Brands that build community get trust, repeat attention, and stronger word-of-mouth.",
  systems: "Founders hit ceilings when everything depends on memory instead of systems.",
  pricing: "Pricing is strategy. Cheap is not automatically attractive if margins disappear.",
  trust: "Reputation compounds slowly and can be damaged quickly. Protect it on purpose.",
  focus: "Every new idea has a hidden cost. Focus creates momentum.",
  resilience: "Good businesses are not built by avoiding shocks, but by surviving them intelligently.",
};
